name: Build Linux

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Select environment"
        required: true
        type: choice
        options:
          - staging
          - production
        default: "staging"

run-name: Build Linux / ${{ github.event.inputs.env }}

jobs:
  build-linux:
    name: Build Linux / ${{ github.event.inputs.env }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - name: Get version
        id: get_version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: ✨ Add version info to summary
        run: |
          echo "# ✅ Build Details" >> $GITHUB_STEP_SUMMARY
          echo "- **Environment:** ${{ github.event.inputs.env }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Version:** v${{ steps.get_version.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Branch:** ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build for Linux
        run: |
          if [ "${{ github.event.inputs.env }}" = "staging" ]; then
            echo "Building for STAGING..."
            npm run dist-linux-staging
          else
            echo "Building for PRODUCTION..."
            npm run dist-linux-production
          fi
