name: Build Linux

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      version:
        required: true
        type: string
      should_run:
        required: true
        type: boolean

jobs:
  build-linux:
    name: Linux Build
    runs-on: ubuntu-latest

    steps:
      - name: Check if should run
        if: ${{ !inputs.should_run }}
        run: echo "Skipping because should_run=false"

      - name: Check out
        if: ${{ inputs.should_run }}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - name: Get version from package.json
        if: ${{ inputs.should_run }}
        id: get_version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Verify input version matches package.json version
        if: ${{ inputs.should_run }}
        run: |
          echo "Input version: ${{ inputs.version }}"
          echo "Package.json version: ${{ steps.get_version.outputs.version }}"
          if [ "${{ inputs.version }}" != "${{ steps.get_version.outputs.version }}" ]; then
            echo "❌ Version mismatch!"
            exit 1
          fi

      - name: Set up Node
        if: ${{ inputs.should_run }}
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        if: ${{ inputs.should_run }}
        run: npm ci

      - name: Configure AWS Credentials
        if: ${{ inputs.should_run }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build for Linux
        if: ${{ inputs.should_run }}
        run: |
          if [ "${{ inputs.env }}" = "Staging" ]; then
            echo "Building for Staging..."
            npm run dist-linux-staging
          else
            echo "Building for Production..."
            npm run dist-linux-production
          fi
